settings:
  name: "NetApp Disaster Recovery"
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    release_notes_autogen:
      release_notes_repo: console-relnotes

sidebar:
  entries:
    - title: NetApp Disaster Recovery docs
      url: /index.html
    - section: release-notes
    - section: get-started
    - section: use
    - section: reference
    - title: FAQ
      url: /get-started/dr-faq.html
    - section: support
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: NetApp Data Services
  repo: data-services-family
