=== BlueXP disaster recovery is now NetApp Disaster Recovery

BlueXP disaster recovery has been renamed to NetApp Disaster Recovery.

=== BlueXP is now NetApp Console
 
BlueXP has been renamed and redesigned to better reflect the role it has in managing your data infrastructure.
 
The NetApp Console (formerly BlueXP) provides centralized management of storage and data services across on-premises and cloud environments at enterprise grade—delivering real-time insights, faster workflows, and simplified administration. For details on what’s changed, see the https://docs.netapp.com/us-en/bluexp-relnotes/index.html[NetApp Console release notes].

=== Other updates 

* Support for Amazon Elastic VMware Service (EVS) with Amazon FSx for NetApp ONTAP was in a public preview. With this release, it is now generally available. For details, refer to link:../reference/evs-deploy-guide-introduction.html[Introduction of NetApp Disaster Recovery using Amazon Elastic VMware Service and Amazon FSx for NetApp ONTAP].
* Storage discovery improvements, including  reduced discovery times for on-premises deployments
* Identity and Access Management (IAM) support, including role-based access control (RBAC) and enhanced user permissions
* Private Preview support for Azure VMware solution and Cloud Volumes ONTAP. With this support, you can now configure disaster recovery protection from on-premises to the Azure VMware solution using Cloud Volumes ONTAP storage.