=== Kubernetes support in NetApp Disaster Recovery is now generally available (GA)

Support for Kubernetes-based workloads in NetApp Disaster Recovery is now generally available (GA). With support for Kubernetes-based workloads, you can protect applications running on Kubernetes clusters, including OpenShift Virtualization environments. Disaster Recovery supports any version of Kubernetes currently supported by Trident Protect, ensuring seamless integration and robust disaster recovery capabilities for containerized applications.

To begin protecting Kubernetes-based workloads, see link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/task-kubernetes-requirements.html[Kubernetes requirements for NetApp Disaster Recovery^].

=== Resource transformations

Disaster Recovery now supports resource transformations, allowing you to modify any aspect of a workload during failover. This feature provides flexibility to adapt workloads to different environments and configurations during a disaster recovery event.

Resource transformations are applied when you create a replication plan. You can create, edit, and delete resource transformations in the new Settings page. For more information, see link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/task-resource-transformation.html[Manage resource transformations^].

=== Script execution

You can now inject custom scripting into the failover workflow to coordinate the quiescence and resumption of applications. This feature helps ensure that applications are properly prepared before a snapshot is replicated and restored appropriately so operations can resume seamlessly after failover.

To learn how to inject a custom script, see link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html[Create a replication plan^].

=== Workloads page

Disaster Recovery has added a Workloads page to the UI, providing a comprehensive view of all discovered workloads and their protection status. The Workloads page enables you to monitor and manage your workloads more effectively.

For more information, see link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/dashboard-view.html[Review health and protection status in Disaster Recovery^].

=== Settings update

Disaster Recovery now provides a Settings page to centrally manage resource transformation templates and AppVaults. This page provides a single interface to configure and manage these critical components of your disaster recovery plans. To learn more about options in the Settings page, see link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/task-resource-transformation.html[Manage resource transformations^] and link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/task-appvault.html[Manage AppVaults^].

=== General improvements

Disaster Recovery has:

* introduced enhanced validations in the replication plan creation page to ensure a smoother, error-free user experience.
* increased the resiliency of the service to tolerate intermittent request timeouts, enhancing the UI's overall performance and reliability.