---
sidebar: sidebar
permalink: reference/dr-reference-roles.html
keywords: how bluexp disaster recovery works, what is disaster recovery, bluexp, vmware, vcenter, draas, replicate, failover, failback, fail over, fail back, vmware cloud, netapp intelligent services
summary: NetApp Disaster Recovery employs roles to govern the access that each user has to specific features and actions.
---

= NetApp Disaster Recovery role-based access to features
:hardbreaks:
:icons: font
:imagesdir: ../media/use

[.lead]
NetApp Disaster Recovery employs roles to govern the access that each user has to specific features and actions. 

The service uses the following roles that are specific to NetApp Disaster Recovery. 

* *Disaster recovery admin*: Perform any actions in NetApp Disaster Recovery.
* *Disaster recovery failover admin*: Perform failover and migrate actions in NetApp Disaster Recovery. 
* *Disaster recovery application admin*: Create and modify replication plans and start test failovers. 
* *Disaster recovery viewer*: View information in NetApp Disaster Recovery, but cannot perform any actions.
    

These roles are specific to NetApp Disaster Recovery and are not the same as the platform roles that are used in the NetApp Console. For details about all NetApp Console platform roles, see https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html[the NetApp Console setup and administration documentation^].

The following table indicates the actions that each NetApp Disaster Recovery role can perform. 

[cols=5*,options="header",cols="30,20a,20a,20a,20a",width="100%"]
|===
| Feature and action
| Disaster recovery admin
| Disaster recovery failover admin
| Disaster recovery application admin
| Disaster recovery viewer

| View dashboard and all tabs | Yes | Yes |Yes |Yes
| Start free trial | Yes | No  |No |No
| Initiate discovery of workloads | Yes | No |No |No
| View license information | Yes | Yes |Yes |Yes
| Activate license | Yes | No  |Yes |No

5+| *On the Sites option*: 
| View sites | Yes | Yes |Yes |Yes
| Add, modify, or delete sites | Yes | No| No |No


5+| *On the Replication plans option*: 
| View replication plans | Yes | Yes  |Yes |Yes
| View replication plan details | Yes | Yes  |Yes |Yes
| Create or modify replication plans | Yes | Yes  |Yes |No
| Create reports | Yes | No |No | No
| View snapshots | Yes | Yes | Yes | Yes
| Perform failover tests | Yes | Yes | Yes |No
| Perform failovers | Yes | Yes  | No |No
| Perform failbacks | Yes | Yes  |No |No
| Perform migations | Yes | Yes  |No |No

5+| *On the Resource groups option*: 
| View resource groups | Yes | Yes  |Yes |Yes
| Create, modify, or delete resource groups| Yes | No | Yes | No


5+| *On the Job Monitoring option*:
| View jobs| Yes | No  |Yes |Yes
| Cancel jobs| Yes | Yes |Yes |No



|===
