---
sidebar: sidebar
permalink: reference/evs-deploy-guide-install-connector.html
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: The NetApp Console agent orchestrates connection and management between the NetApp Console and cloud or on-prem storage resources. 

---
= Install the NetApp Console agent for NetApp Disaster Recovery

:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
Install a NetApp Console agent so NetApp Disaster Recovery can communicate with and manage your cloud and on-premises infrastructure.

For NetApp Disaster Recovery, these actions orchestrate VMware vCenter clusters and ONTAP storage instances by using each service's native APIs to provide protection for production VMs running in an on-premises location. Although the Console agent can be installed in any of your network locations, we recommend installing the Console agent at the disaster recovery site for NetApp Disaster Recovery. Installing at the disaster recovery site ensures that in the event of a failure of the primary site, the NetApp console UI maintains its connection to the Console agent and can orchestrate the recovery process within that disaster recovery site.

== Installation 

* To use Disaster Recovery, install the Console agent in standard mode. To learn more about the types of Console agent installations, visit https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html[Learn about NetApp Console deployment modes^].

The specific installation steps for the Console agent depend on your deployment type. See link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html[Learn about Console agents^] for more information.  

[TIP]
The simplest method for installing the Console agent with Amazon AWS is to use the AWS Marketplace. For details about Console agent installation using the AWS Marketplace, see https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html[Create a Console agent from the AWS Marketplace^].
