---
sidebar: sidebar
permalink: reference/evs-deploy-guide-config-prereqs.html
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: You should ensure that several prerequisites are met before you continue to configure Amazon EVS with NetApp Disaster Recovery. 

---
= Prerequisites for Amazon EVS with NetApp Disaster Recovery

:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
Before you configure Amazon EVS with NetApp Disaster Recovery, review and meet these requirements. 


.Prerequisites 
* Review the link:../get-started/dr-prerequisites.html[general prerequisites for Disaster Recovery].
* Create a vCenter user account with the VMware privileges NetApp Disaster Recovery requires. 
+
NOTE: Do **not** use the default "\administrator@vsphere.com" administrator account. Instead, you should create a NetApp Disaster Recovery-specific user account on all vCenter clusters that will participate in the disaster recovery process. For a list of specific privileges required, see link:vcenter-privileges.html[vCenter privileges needed for NetApp Disaster Recovery]. 

* Ensure that all vCenter datastores hosting VMs protected by Disaster Recovery are on NetApp ONTAP storage. 
+
When you use Amazon FSx for NetApp ONTAP, Disaster Recovery supports NFS and VMFS on iSCSI, but not FC. Although Disaster Recovery supports FC, Amazon FSx for NetApp ONTAP does not.

* Ensure your Amazon EVS vCenter is connected to an Amazon FSx for NetApp ONTAP storage cluster.

* Ensure VMware tools are installed on all protected VMs.

* Ensure that your on-premises network connects to your AWS VPC by using an Amazon-approved connection method. It's recommended you use AWS Direct Connect, AWS Private Link, or an AWS Site-to-Site VPN.

* Review and ensure compliance with the connection and port requirements for EVS with Disaster Recovery: 
+
[cols=4, options="header"]
|===
| Source | Destination | Port | Details 
| Amazon FSxN | On-premises ONTAP | TCP 11104, 11105, ICMP | SnapMirror 
| On-premises ONTAP | Amazon FSxN | TCP 11104, 11105, ICMP | SnapMirror 
| NetApp Console agent | On-premises ONTAP | TCP 443, ICMP only | API calls 
| NetApp Console agent | Amazon FSxN | TCP 441, ICMP only | API calls 
| NetApp Console agent | vCenter (on-premises, EVS), ESXi host (on-premises, EVS) | 443 | API calls, script execution
|===
