---
sidebar: sidebar
permalink: reference/evs-deploy-guide-introduction.html
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Introduction of NetApp Disaster Recovery using Amazon EVS and Amazon FSx for NetApp ONTAP.
---
= Learn about NetApp Disaster Recovery with Amazon Elastic VMware Service and Amazon FSx for NetApp ONTAP

:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
NetApp Disaster Recovery helps protect VMware workloads by replicating data from on-premises environments to Amazon EVS and Amazon FSx for NetApp ONTAP for disaster recovery.

//NOTE: THIS DOCUMENTATION REGARDING AMAZON EVS IS PROVIDED AS A TECHNOLOGY PREVIEW. With this preview offering, NetApp reserves the right to modify offering details, contents, and timeline before General Availability. 

One of the primary challenges with any DR solution is managing the incremental cost of purchasing, configuring, and maintaining additional compute, network, and storage resources just to provide a DR replication and recovery infrastructure. One popular option for protecting critical on-premises virtual resources is to use cloud-hosted virtual resources as the DR replication and recovery infrastructure. Amazon is one example of such a solution that can provide cost-effective resources that are compatible with NetApp ONTAP hosted VM infrastructures.

Amazon introduced its Amazon Elastic VMware Service (Amazon EVS) that enables VMware Cloud Foundation within your virtual private cloud (VPC). Amazon EVS provides the resilience and performance of AWS along with familiar VMware software and tools, enabling Amazon EVS vCenters to integrate with your on-premises virtualized infrastructure.

While Amazon EVS comes with included storage resources, using native storage can reduce its effectiveness for organizations with storage-heavy workloads. In these cases, teaming Amazon EVS with Amazon FSx for NetApp ONTAP storage (Amazon FSxN) can provide a more flexible storage solution. In addition, when you are using NetApp ONTAP storage solutions on-premises to host your VMware infrastructure, using Amazon EVS with FSx for ONTAP provides data interoperability and protection features across on-premises and cloud environments.

For information about Amazon FSx for NetApp ONTAP, see https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html[Getting started with Amazon FSx for NetApp ONTAP^].
