---
sidebar: sidebar
permalink: use/task-appvault.html
keywords: disaster recovery, appvault, update credentials, trident protect, kubernetes, edit endpoints
summary: Managing AppVaults in Disaster Recovery enables you to review the connectivity status of your AppVaults as well as the credentials and endpoints for the AppVaults to ensure the continuity of your disaster recovery plans.
---

= Manage AppVaults in NetApp Disaster Recovery
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
NetApp Disaster Recovery workloads with Kubernetes use AppVault, a cloud storage target where Trident Protect saves Kubernetes protection data. Managing AppVaults enables you to review the connectivity status of your AppVaults as well as the credentials and endpoints for the AppVaults to ensure the health of your replication plans. 

== Add an AppVault

You can add an AppVault when you create a replication plan for Kubernetes or create one from the Settings page. 

.Steps
. In Disaster Recovery, select *Settings* from the sidebar.
. In the AppVault card, select *+ Add AppVault*. 
. Enter a *Name* and select the *Console agent* the AppVault should be connected to. 
. Select the cloud *Provider* for hosting the *AppVault*. 
. Based on the provider selection, Disaster Recovery populates existing configured cloud subscriptions.
+
For Azure, choose the *Subscription*, *Resource group*, and *Storage account*.
+
For AWS, ONTAP S3, and StorageGRID, choose the *Account* or *Credentials* and *Bucket*.
. If you selected ONTAP S3 or StorageGRID, you can optionally add credentials. Select *Add credentials* to expand the options, then add the *Credential name*, *Gateway node FQDN*, the *Port* number, *Access key*, and *Secret key*. 
. Select **Add**. 

== Update AppVault credentials

If the credentials for your AppVault have changed, update them in the Settings page to ensure continuity of your replication plans. Updating the credentials will replace the keys for every AppVault that shares this credential.

.Steps
. In Disaster Recovery, select *Settings* from the sidebar.
. Select *Manage AppVaults*. 
. Find the AppVault you want to update. From the action menu, select *Update*.
. Review the number of AppVaults and replication plans affected by the change. 
. Enter the new *Secret key* and *Access key*.
. Select *Update credentials* to apply the changes. 

== Edit AppVault credentials

If the connection settings to your AppVault have changed, update them to ensure the continuity of your replication plans for Kubernetes workloads. 

.Steps
. In Disaster Recovery, select *Settings* from the sidebar.
. Select *Manage AppVaults*. 
. Find the AppVault you want to edit. From the action menu, select *Edit*.
. Enter the new endpoint for your AppVault.
. Select *Save* to apply the new endpoint. 


== Delete an AppVault

If you no longer need an AppVault, you can delete it. 

.Steps
. In Disaster Recovery, select *Settings* from the sidebar.
. Select *Manage AppVaults*. 
. Find the AppVault you want to delete. From the action menu, select *Delete*.
. In the dialog window, select *Delete* to confirm the action. 