---
sidebar: sidebar
permalink: get-started/dr-prerequisites.html
keywords: what are disaster recovery requirements, disaster recovery prerequisites, bluexp, disaster recovery
summary: Before using NetApp Disaster Recovery, you should ensure that your environment meets the ONTAP storage, VMware vCenter cluster, and NetApp Console requirements. 
---

= NetApp Disaster Recovery prerequisites
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Before using NetApp Disaster Recovery, you should ensure that your environment meets the ONTAP storage, VMware vCenter cluster, and NetApp Console requirements. 



== ONTAP storage prerequisites

These prerequisites apply to either ONTAP or Amazon FSX for NetApp ONTAP instances.

* Source and destination clusters must have a peer relationship. 
* The SVM that will host the disaster recovery volumes must exist on the destination cluster.
* The source SVM and destination SVM must have a peer relationship. 
+
NOTE: Disaster recovery volumes in the destination SVM or SVMs should not be created ahead of time. NetApp Disaster Recovery will create the destination volumes as needed for the replication plan.

* If deploying with Amazon FSx for NetApp ONTAP, the following prerequisite applies: 
** An Amazon FSx for NetApp ONTAP instance to host VMware DR datastores must exist in your VPC. Refer to Amazon FSx for ONTAP documentation on https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html[how to get started^]. 



== VMware vCenter clusters prerequisites

These prerequisites apply to both on-premises vCenter clusters and to VMware Cloud for AWS software-defined data center (SDDC).


* Review link:../reference/vcenter-privileges.html[vCenter privileges] required for NetApp Disaster Recovery. 
* All VMware clusters that you want NetApp Disaster Recovery to manage must be hosted on ONTAP volumes.
* All VMware datastores to be managed by NetApp Disaster Recovery must use one of the following protocols: 
** NFS 
** VMFS using the iSCSI or FC protocol 

* VMware vSphere version 7.0 Update 3 (7.0v3) or later
* If you are using VMware Cloud SDDC, these prerequisites apply. 
** In the VMware Cloud Console, use the service roles of Administrator and NSX Cloud Administrator. Also use the organization owner for the Organization role. Refer to https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html[Using VMware Cloud Foundations with AWS FSx for NetApp ONTAP documentation^]. 

** Link the VMware Cloud SDDC with Amazon FSx for NetApp ONTAP instance. Refer to https://vmc.techzone.vmware.com/fsx-guide#overview[VMware Cloud on AWS integration with Amazon FSx for NetApp ONTAP deployment information^].



== NetApp Console prerequisites

=== Get started with the NetApp Console

If you haven't already done so, https://docs.netapp.com/us-en/bluexp-setup-admin/task-sign-up-saas.html[sign up to the NetApp Console and create an organization^].

=== Gather credentials for ONTAP and VMware

* Amazon FSx for ONTAP and AWS credentials must be added to the working environment within the NetApp Console project that will be used to manage NetApp Disaster Recovery.

* NetApp Disaster Recovery requires vCenter credentials. You enter the vCenter credentials when you're adding a site in NetApp Disaster Recovery. 
+
For a list of vCenter privileges needed, refer to link:../reference/vcenter-privileges.html[vCenter privileges needed for NetApp Disaster Recovery]. 
For instructions on how to add a site, refer to link:../use/sites-add.html[Add a site].

=== Create the NetApp Console agent

A Console agent must be set up in the NetApp Console. When you use the agent, it will include the appropriate capabilities for the disaster recovery service.
 
* NetApp Disaster Recovery works only with the standard mode agent deployment. See https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html[Getting started with the NetApp Console in standard mode^]. 
* Ensure that both the source and destination vCenters use the same Console agent. 
* Type of Console agent needed:
** *On-premises to on-premises disaster recovery*: Install the Console on-premises agent in the disaster recovery site. Refer to https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html[Install and set up the Console agent on premises^].
** *On-premises to AWS*: Install the Console agent for AWS in your AWS VPC. Refer to https://docs.netapp.com/us-en/bluexp-setup-admin/concept-install-options-aws.html[Console agent installation options in AWS^].
+
TIP: For on-premises to on-premises, use the on-premises Console agent. For on-premises to AWS, use the AWS Console agent, which has access to the source on-premises vCenter and the destination on-premises vCenter.
//** The on-premises and cloud Connector should have connectivity to both the on-premises and VMware Cloud (VMC) VCenter with ESXis. This enables the backup, failover, failback and migration features to work properly with the needed networking and script features.
** The installed Console agent must be able to access any VMware cluster that NetApp Disaster Recovery will manage. 
* All ONTAP arrays to be managed by NetApp Disaster Recovery must be added to any system within the NetApp Console project that will be used to manage NetApp Disaster Recovery.
+
See https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[Discover on-premises ONTAP clusters^]. 


* For information about setting up an intelligent proxy for NetApp Disaster Recovery, see link:../get-started/dr-setup.html[Set up your infrastructure for NetApp Disaster Recovery].

== Workload prerequisites
To ensure that application-consistency processes are successful, apply these prerequisites: 

* Ensure that VMware tools (or Open VM tools) are running on the VMs that will be protected. 
* For Windows VMs running Microsoft SQL Server or Oracle Database or both, the databases should have their VSS Writers enabled. 
* Oracle databases that are running on a Linux operating system should have the operating system user authentication enabled for the Oracle database SYSDBA role.  



