---
sidebar: sidebar
permalink: get-started/dr-prerequisites.html
keywords: what are disaster recovery requirements, disaster recovery prerequisites, bluexp, disaster recovery
summary: Before using NetApp Disaster Recovery, ensure your environment meets the ONTAP storage, VMware vCenter cluster, and NetApp Console requirements. 
---

= NetApp Disaster Recovery prerequisites
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Before using NetApp Disaster Recovery, ensure your environment meets the ONTAP storage, VMware vCenter cluster, and NetApp Console requirements. 

== Software versions

[cols=2*,options="header",cols="35,55a",width="100%"]
|===
| Component
| Minimum version

| Amazon FSx for NetApp ONTAP | Latest available version 
| Google Cloud VMware Engine using Google Cloud NetApp Volumes | Latest available version 
| ONTAP software | ONTAP 9.10.0 or later
| VMware Cloud for AWS | Latest available version
| VMware on-premises vCenter | 7.0u3 or later

|=== 

== Google Cloud prerequisites and considerations

With Disaster Recovery on Google Cloud VMware Engine using Google Cloud NetApp Volumes, ensure you configure the correct permissions and adhere to the noted considerations. 

* You must link:https://docs.google.com/forms/d/1zuaHu437MNpUf8i5oByK-OTLWXcNIg0es9t036riYRc/viewform?edit_requested=true[File a request to allow-list your volumes hybrid replication^].
* Be aware of the link:https://docs.cloud.google.com/netapp/volumes/docs/quotas[Google Cloud NetApp Volumes quota and limits^].
* The Google project with the VMware engine needs to be allow-listed for creating, mounting, and unmounting datastores. Contact the Google SRE team for allow-listing. 
* You can only add one volume or datastore to a replication plan. 
* Review the link:../release-notes/dr-limitations.html#limitations-with-google-cloud-netApp-volumes[limitations].

**Failover considerations**

* Failover is only supported using the latest snapshot. If necessary, you can create a new snapshot during snapshot (that is, the selective snapshot option must be disabled).
* You can't create a new snapshot after failover.
* You can't retain and reconcile snapshots after failover. 

**Failback considerations**

* Failback is only possible with the selective snapshot option. You can't perform a failback by taking a new snapshot. 
* If you remove cluster peering between on-premises storage and Google Cloud NetApp Volumes storage clusters, you must manually clear the cluster and storage VM peering entry from the on-premises cluster. For more information, see link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-delete.html[Delete a vserver peer relationship^].

=== Google Cloud permissions

The service principal in Google Cloud should be assigned the following roles or equivalent permissions:

- link:https://docs.cloud.google.com/compute/docs/access/iam[Compute Admin role^]
- link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html[Google Cloud Permissions for NetApp Console^]
- link:https://docs.cloud.google.com/iam/docs/roles-permissions/netapp[Google Cloud NetApp Volumes Admin]
- link:https://docs.cloud.google.com/vmware-engine/docs/iam#vmware-engine-roles[VMware Engine Service Admin^]

=== NetApp Console permissions

The NetApp Console user must have the following roles:

* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-gcnv-roles.html[Google Cloud NetApp Volumes admin^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html#data-service-roles[SnapCenter admin^]
* link:https://docs.netapp.com/us*-en/console-setup-admin/reference-iam-disaster-rec-roles.html[Disaster Recovery failover admin^]

== ONTAP storage prerequisites

These prerequisites apply to either ONTAP or Amazon FSX for NetApp ONTAP instances.

* Source and destination clusters must have a peer relationship. 
* The SVM that hosts the disaster recovery volumes must exist on the destination cluster.
* The source SVM and destination SVM must have a peer relationship. 
* If deploying with Amazon FSx for NetApp ONTAP, the following prerequisite applies: 
** An Amazon FSx for NetApp ONTAP instance to host VMware DR datastores must exist in your VPC. To get started, see link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html[the Amazon FSx for ONTAP documentation^]. 

== VMware vCenter clusters prerequisites

These prerequisites apply to both on-premises vCenter clusters and to VMware Cloud for AWS software-defined data center (SDDC).


* Review link:../reference/vcenter-privileges.html[vCenter privileges] required for NetApp Disaster Recovery. 
* All VMware clusters that you want NetApp Disaster Recovery to manage use ONTAP volumes to host any VMs that you want to protect.
* All VMware datastores to be managed by NetApp Disaster Recovery must use one of the following protocols: 
** NFS 
** VMFS using the iSCSI or FC protocol 

* VMware vSphere version 7.0 Update 3 (7.0v3) or later
* If you are using VMware Cloud SDDC, these prerequisites apply. 
** In the VMware Cloud Console, use the service roles of Administrator and NSX Cloud Administrator. Also use the organization owner for the Organization role. Refer to https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html[Using VMware Cloud Foundations with AWS FSx for NetApp ONTAP documentation^]. 

** Link the VMware Cloud SDDC with Amazon FSx for NetApp ONTAP instance. Refer to https://vmc.techzone.vmware.com/fsx-guide#overview[VMware Cloud on AWS integration with Amazon FSx for NetApp ONTAP deployment information^].



== NetApp Console prerequisites

=== Get started with the NetApp Console

If you haven't already done so, https://docs.netapp.com/us-en/console-setup-admin/task-sign-up-saas.html[sign up to the NetApp Console and create an organization^].

=== Gather credentials for ONTAP and VMware

* Amazon FSx for ONTAP and AWS credentials must be added to the system within the NetApp Console project that manages NetApp Disaster Recovery.

* NetApp Disaster Recovery requires vCenter credentials. You enter the vCenter credentials when you're adding a site in NetApp Disaster Recovery. 
+
For a list of vCenter privileges needed, refer to link:../reference/vcenter-privileges.html[vCenter privileges needed for NetApp Disaster Recovery]. 
For instructions on how to add a site, refer to link:../use/sites-add.html[Add a site].

=== Create the NetApp Console agent

The Console agent is a software component that enables the Console to communicate with your ONTAP storage and VMware vCenter clusters. It is required for Disaster Recovery to function properly. The agent resides in your private network (either an on-premises data center or a cloud VPC) and communicates with your ONTAP storage instances and any additional server and application components. For Disaster Recovery, this is access to your managed vCenter clusters. 

A Console agent must be set up in the NetApp Console. When you use the agent, it will include the appropriate capabilities for the Disaster Recovery service.
 
* NetApp Disaster Recovery works only with the standard mode agent deployment. See https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html[Getting started with the NetApp Console in standard mode^]. 
* Ensure that both the source and destination vCenters use the same Console agent. 
* Type of Console agent needed:
** *On-premises to on-premises disaster recovery*: Install the Console on-premises agent in the disaster recovery site. Using this method, a failure of the primary site doesn't prevent the service from restarting your virtual resources at the DR site. Refer to https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-on-prem.html[Install and set up the Console agent on premises^].
** *On-premises to AWS*: Install the Console agent for AWS in your AWS VPC. Refer to https://docs.netapp.com/us-en/console-setup-admin/concept-install-options-aws.html[Console agent installation options in AWS^].
+
TIP: For on-premises to on-premises, use the on-premises Console agent. For on-premises to AWS, use the AWS Console agent, which has access to the source on-premises vCenter and the destination on-premises vCenter.
** The installed Console agent must be able to access any VMware vCenter cluster instances and ESXi hosts managed by those vCenter clusters that Disaster Recovery will manage.

* All ONTAP arrays to be managed by NetApp Disaster Recovery must be added to any system within the NetApp Console project that will be used to manage NetApp Disaster Recovery.
+
See https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html[Discover on-premises ONTAP clusters^]. 


* For information about setting up an intelligent proxy for NetApp Disaster Recovery, see link:../get-started/dr-setup.html[Set up your infrastructure for NetApp Disaster Recovery].

== Workload prerequisites

To ensure that application-consistency processes are successful, apply these prerequisites: 

* Ensure that VMware tools (or Open VM tools) are running on the VMs that will be protected. 
* For Windows VMs running Microsoft SQL Server, Oracle Database, or both, the databases must have their VSS Writers enabled. 
* Oracle databases that are running on a Linux operating system must have the operating system user authentication enabled for the Oracle database SYSDBA role.  



