---
sidebar: sidebar
permalink: get-started/dr-setup.html
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap
summary: To use NetApp Disaster Recovery, perform a few steps to set it up.    
---

= Set up your infrastructure for NetApp Disaster Recovery
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
To use NetApp Disaster Recovery, perform a few steps to set it up both in Amazon Web Services (AWS) and in the NetApp Console.  

TIP: Review link:../get-started/dr-prerequisites.html[prerequisites] to ensure that your system is ready.

== Get ready for NetApp Disaster Recovery for on-premises-to-on-premises protection

Ensure that the following requirements are met before you set up NetApp Disaster Recovery for on-premises-to-on-premises protection:

* ONTAP storage
** Ensure that you have ONTAP credentials.
** Create or verify your disaster recovery site.
** Create or verify your destination ONTAP SVM.
** Ensure that your source and destination ONTAP SVMs are peered.
* vCenter clusters
** Ensure that the VMs you want to protect are hosted on NFS datastores (using ONTAP NFS volumes) or VMFS datastores (using NetApp iSCSI LUNs).
** Review link:../reference/vcenter-privileges.html[vCenter privileges] required for NetApp Disaster Recovery. 
** Create a disaster recovery user account (not the default vCenter admin account) and assign the vCenter privileges to the account.

=== Intelligent proxy support 

The NetApp Console agent supports intelligent proxy. Intelligent proxy is a lightweight, secure, and efficient way to connect your on-premises environment to the NetApp Console. It provides a secure connection between your system and the Console service without requiring a VPN or direct internet access. This optimized proxy implementation offloads API traffic within the local network.

When a proxy is configured, NetApp Disaster Recovery attempts to communicate directly with VMware or ONTAP and uses the configured proxy if direct communication fails.

NetApp Disaster Recovery proxy implementation requires port 443 communication between the Console agent and any vCenter Servers and ONTAP arrays using an HTTPS protocol. The NetApp Disaster Recovery agent within the Console agent communicates directly with VMware vSphere, the VC, or ONTAP when performing any actions.
 
For more information about general proxy set up in the NetApp Console, see https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html[Configure the Console agent to use a proxy server^].

== Get ready for NetApp Disaster Recovery for on-premises-to-cloud protection using AWS

To set up NetApp Disaster Recovery for on-premises-to-cloud protection using AWS, you need to set up the following:

* Set up AWS FSx for NetApp ONTAP
* Set up VMware Cloud on AWS SDDC


=== Set up AWS FSx for NetApp ONTAP

* Create an Amazon FSx for NetApp ONTAP file system. 
** Provision and configure FSx for ONTAP. Amazon FSx for NetApp ONTAP is a fully managed service that provides highly reliable, scalable, high-performing, and feature-rich file storage, built on the NetApp ONTAP file system.
 
** Follow the steps in https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html[Technical Report 4938: Mount Amazon FSx ONTAP as an NFS datastore with VMware Cloud on AWS^] and https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html[Quick start for Amazon FSx for NetApp ONTAP] to provision and configure FSx for ONTAP.
 
* Add Amazon FSx for ONTAP to the system, and add AWS credentials for FSx for ONTAP.
* Create or verify your destination ONTAP SVM in AWS FSx for ONTAP instance.
* Configure replication between your source on-premises ONTAP cluster and your FSx for ONTAP instance in the NetApp Console. 


Refer to https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html[how to set up an FSx for ONTAP system^] for detailed steps.



=== Set up VMware Cloud on AWS SDDC

https://www.vmware.com/products/vmc-on-aws.html[VMware Cloud on AWS^] provides a cloud-native experience for VMware-based workloads in the AWS ecosystem. Each VMware software-defined data center (SDDC) runs in an Amazon Virtual Private Cloud (VPC) and provides a full VMware stack (including vCenter Server), NSX-T software-defined networking, vSAN software-defined storage, and one or more ESXi hosts that provide compute and storage resources to the workloads.
 
To configure a VMware Cloud environment on AWS, follow the steps in https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html[Deploy and configure the Virtualization Environment on AWS^]. A pilot-light cluster can also be used for disaster recovery purposes.
 

