---
sidebar: sidebar
permalink: get-started/reference-vmware-prerequisites.html
keywords: vmware cluster prerequisites, vmware 
summary: Before using NetApp Disaster Recovery, ensure your environment meets the VMware vCenter cluster requirements. 
---

= VMware vCenter clusters prerequisites for NetApp Disaster Recovery
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Before using NetApp Disaster Recovery, ensure your environment meets the VMware vCenter cluster requirements. 

== General prerequisites 

These prerequisites apply to both on-premises vCenter clusters and to VMware Cloud for AWS software-defined data center (SDDC).

* Review link:../reference/vcenter-privileges.html[vCenter privileges] required for NetApp Disaster Recovery. 
* All VMware clusters that you want NetApp Disaster Recovery to manage use ONTAP volumes to host any VMs that you want to protect.
* All VMware datastores to be managed by NetApp Disaster Recovery must use one of the following protocols: 
** NFS 
** VMFS using the iSCSI or FC protocol 
* VMware vSphere version 7.0 Update 3 (7.0v3) or later

== VMware Cloud SDDC prerequisites

If you are using VMware Cloud SDDC, these additional prerequisites apply:

* In the VMware Cloud Console, use the service roles of Administrator and NSX Cloud Administrator. Also use the organization owner for the Organization role. Refer to https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html[Using VMware Cloud Foundations with AWS FSx for NetApp ONTAP documentation^]. 
* Link the VMware Cloud SDDC with Amazon FSx for NetApp ONTAP instance. Refer to https://vmc.techzone.vmware.com/fsx-guide#overview[VMware Cloud on AWS integration with Amazon FSx for NetApp ONTAP deployment information^].